### ISSUE TITLE
Fig 9.9 Pg 260: Clarification for a slanted arrow through a box

### ISSUE THREAD

**Issue by solomonbstoner** [sdrforengineers/bookerrata#10]
What does the slanted arrow through a box mean about e(n)? I've never seen it before. It looks like a variable resistor.
I also see it used in [another paper](https://www.researchgate.net/publication/3325701_An_efficient_systolic_architecture_for_the_DLMS_adaptive_filter_and_its_applications), but I have no idea what it represents.

Is it just a convention for representing an error signal being used as an input to a block? 

![Screenshot from 2021-08-22 21-51-59](https://user-images.githubusercontent.com/24548334/130357866-65b2dd80-1b7f-4158-b2c7-add3861a6d90.png)

**Comment by tfcollins** [comment]
It means that it updates the taps of the filter or gain of the component.

-Travis

**Comment by solomonbstoner** [comment]
Awesome! Thanks!
