### ISSUE TITLE
Chp 8 Pg 232: Clarification needed

### ISSUE THREAD

**Issue by solomonbstoner** [sdrforengineers/bookerrata#3]
Could someone clarify what the following sentence taken from Section 8.1 (Page 232) means? "if only bits are consult the relative gain of the signal is removed, which is information that is useful when determining if signal is present". This sentence does not make any sense.

![Screenshot from 2021-08-19 21-21-17](https://user-images.githubusercontent.com/24548334/130076081-00223d10-ae4c-4bb3-b6b4-11e1445e3c26.png)

**Comment by tfcollins** [comment]
These are a couple of typos: consult->consulted and if signal->if a signal

This basically means if you quantize/cast the signal to bits from symbols you lose information. For example, for a 12-bit ADC if I received the values 256,-300,800 (1,0,1 through a quantizer) that is very different than 5,-10,2 (1,0,1 through same quantizer). The first would likely indicate the presence of a signal, the second is just likely noise.

**Comment by solomonbstoner** [comment]
Ok, so the values "256,-300,800" show relative greater gain than "5,-10,2", indicating the first is more likely to be a signal than the second. But putting both through a binary slicer (using GNU Radio term) would convert both to "1,0,1", removing the relative gain property, making it difficult to determine whether a signal is really present. I get it now. Thank you!
