### ISSUE TITLE
Chp 5 Pg 186: IQ imbalance correction

### ISSUE THREAD

**Issue by solomonbstoner** [sdrforengineers/bookerrata#5]
In Section 5.2.4, it is mentioned, "There will always be some residual imbalance, but corrections are performed during initialization so it will not be improved over time necessarily". The 2nd part of the sentence does not seem to make sense. 

![Screenshot from 2021-08-20 08-32-34](https://user-images.githubusercontent.com/24548334/130160931-60d10c0c-a181-4176-ba3b-ff451bc26798.png)

I get that residual imbalance refers to leftover IQ imbalance that will always be present despite corrections. If I were to guess what the sentence means to say, Id say it means to say that IQ imbalance is corrected during initialization so that residual imbalance does not get worse over time. What exactly is it that will "not be improved over time necessarily"?

**Comment by tfcollins** [comment]
IQ imbalance is corrected adaptively in modern devices. However, is only done at initialization for transmitters since you cannot easily probe transmitters at runtime. Receivers will have tracking calibrations that can handle post initialization IQ imbalance.

**Comment by solomonbstoner** [comment]
I see! So the sentence means to say that transmitter IQ imbalance gets corrected at initialization, but cannot be improved during runtime. That makes sense now. Thanks!
