### ISSUE TITLE
Sec 5.2.6 Pg 187: How does mixing signals cause problems? 

### ISSUE THREAD

**Issue by solomonbstoner** [sdrforengineers/bookerrata#6]
In Section 5.2.6, it is mentioned that how signals mix can cause problems, but there is no elaboration on how. Neither is there an explanation of how the Pluto SDR's single-ended LO contributes to or solves the problem. Section 2.3.1 describes how the signal is frequency translated from baseband to the desired frequency (or vice versa), but does not mention what problem the mixing might cause. 

![Screenshot from 2021-08-20 08-38-32](https://user-images.githubusercontent.com/24548334/130161369-bfd72fa5-c24e-4ba8-801b-75da34da8fe7.png)

What problem does mixing cause, and how does a single-ended LO contribute to or mitigate the problem?

**Comment by tfcollins** [comment]
There is an article here about mixers with transceivers and their issues: https://www.analog.com/en/analog-dialogue/articles/complex-mixers-zif-architecture-advanced-algorithms-black-magic-next-generation-sdr-transceivers.html

**Comment by solomonbstoner** [comment]
Oh. So the problem is an image signal produced as a result mixing. Got it now. Thanks!
