### ISSUE TITLE
Sec 8.4.3 Pg 248: LDPC and IEEE 802.11

### ISSUE THREAD

**Issue by solomonbstoner** [sdrforengineers/bookerrata#8]
What does "1944 IEEE 802.11n/ac" mean in the sentence shown below?
Does it mean to quote the 802.11n/ac standard as an example of a system that uses LDPC with 1944 as the block length?
The closest I found that might suggest so is [this paper](https://ieeexplore.ieee.org/document/4708787) which says "LDPC decoder chip for (1944,972) QC-LDPC codes in IEEE 802.11n communication system". Not sure if (1944,972) means 1944 as the block length. 

![Screenshot from 2021-08-22 12-04-31](https://user-images.githubusercontent.com/24548334/130341780-3738113d-a259-489a-8d1f-b9cdef423022.png)

**Comment by solomonbstoner** [comment]
Also, there is a typo in the sentence below what the screenshot shows.
> need to encode a significant amount of bits compared to the other codes to utilize ~~LPDC~~ LDPC efficiently in many cases.

**Comment by tfcollins** [comment]
LDPC will use a parity matrix to encode/decode the data. The dimension of the matrices is related to the block size (number of bits). For 802.11 n/ac the matrix is of size (1944,972) I believe.

**Comment by solomonbstoner** [comment]
I see. So IEEE 802.11n/ac was used as an example of block length 1944. I was confused because I thought "1944 IEEE 802.11n/ac" was a phrase. Thanks Travis!
